openapi: 3.0.1
info:
  title: striveBooks API
  description: book Library
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local server
  - url: https://strive-d7-test.herokuapp.com
    description: Cloud server
tags:
  - name: books
    description: Operations about books
  - name: files
    description: Operation about files
  - name: xml
    description: Usage of xmlbuilder
  - name: attendees  
paths:
  /books:
    get:
      tags: 
        - books
      responses:
        "200":
          description: Cloud server
            
   